#!/bin/sh

ME=`whoami`
DOTFILES=~/.dotfiles
REPO_ID=justinforce/dotfiles
SSH_REPO=git@github.com:$REPO_ID
HTTPS_REPO=https://github.com/$REPO_ID

install_rvm() {
  curl -L https://get.rvm.io | bash -s stable
}

reload_rvm() {
  source ~/.rvm/scripts/rvm
  rvm reload
}

install_ruby_requirements() {
  $(rvm requirements | grep 'For ruby:' -A1 | tail -n1)
}

install_ruby() {
  rvm 2.0.0 --install --default
}

choose_repo() {
  if [ $ME = 'force' ]; then
    REPO=$SSH_REPO
  else
    REPO=$HTTPS_REPO
  fi
}

clone_or_update_repo() {
  if [ -e $DOTFILES ]; then
    cd $DOTFILES
    git pull origin master
  else
    git clone --recursive $REPO $DOTFILES
  fi
}

run_rake_task() {
  cd $DOTFILES
  rake force
}

main() {
  install_rvm
  reload_rvm
  install_ruby_requirements
  install_ruby
  choose_repo
  clone_or_update_repo
  run_rake_task
}

main

:
