#!/bin/bash

DOTFILES=~/.dotfiles
REPO=https://github.com/justinforce/dotfiles

install_rvm_and_ruby() {
  # --ignore-dotfiles will avoid updating my dotfiles, which I manage
  curl -L https://get.rvm.io | bash -s stable --ignore-dotfiles --ruby
}

source_rvm() {
  for path in ~/.rvm/scripts/rvm /etc/profile.d/rvm.sh; do
    [ -e $path ] && source $path
  done
}

clone_or_update_repo() {
  if [ -e $DOTFILES ]; then
    cd $DOTFILES
    git pull origin master
    git submodule sync
    git submodule update --init
  else
    git clone --recursive $REPO $DOTFILES
  fi
}

run_rake_task() {
  cd $DOTFILES
  source_rvm
  rake force
}

main() {
  echo -e "\e[1;32mReticulating splines...\e[m"
  install_rvm_and_ruby
  clone_or_update_repo
  run_rake_task
}

main

:
