#!/bin/sh

if [ "$1" = "inner" ]; then
  branch=$(git branch | grep '*' | sed 's/\*\s*//')
  if [ "$branch" = "(no branch)" ]; then
    git checkout master
  fi
  git pull
else
  git submodule sync
  git submodule foreach `pwd`/$0 inner
fi
