#!/bin/sh

set -e

vundle_path="$HOME/.vim/bundle/vundle"
plugins_path="$HOME/.vim/plugins.vim"
repo='https://github.com/gmarik/vundle.git'

if [ -e $vundle_path ]; then
  cd $vundle_path
  git pull --depth=1 origin master
else
  git clone --depth=1 $repo $vundle_path
fi

# -c 'set nomore' keeps it from hanging when running in a really tiny window
vim -u $plugins_path -c 'set nomore' -c 'BundleInstall!' -c 'qall'
