#!/bin/sh

VUNDLE_PATH=~/.vim/bundle/vundle
PLUGINS_PATH=~/.vim/plugins.vim
REPO=https://github.com/gmarik/vundle.git

if [ -e $VUNDLE_PATH ]; then
  cd $VUNDLE_PATH && git pull --depth=1 origin master
else
  git clone --depth=1 $REPO $VUNDLE_PATH
fi

# -c 'set nomore' keeps it from hanging when running in a really tiny window
vim -u $PLUGINS_PATH -c 'set nomore' -c 'BundleInstall!' -c 'qall'
