set nocompatible
filetype off

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'

Bundle 'Lokaltog/vim-easymotion'
Bundle 'Valloric/YouCompleteMe'
Bundle 'altercation/vim-colors-solarized'
Bundle 'bronson/vim-trailing-whitespace'
Bundle 'chikamichi/mediawiki.vim'
Bundle 'chrisbra/csv.vim'
Bundle 'ekalinin/Dockerfile.vim'
Bundle 'godlygeek/tabular'
Bundle 'honza/vim-snippets'
Bundle 'kchmck/vim-coffee-script'
Bundle 'kien/ctrlp.vim'
Bundle 'majutsushi/tagbar'
Bundle 'mattn/gist-vim'
Bundle 'mattn/webapi-vim'
Bundle 'mileszs/ack.vim'
Bundle 'mmalecki/vim-node.js'
Bundle 'othree/html5.vim'
Bundle 'pangloss/vim-javascript'
Bundle 'saltstack/salt-vim'
Bundle 'scrooloose/nerdtree'
Bundle 'scrooloose/syntastic'
Bundle 'sjl/gundo.vim'
Bundle 'slim-template/vim-slim'
Bundle 'tomasr/molokai'
Bundle 'tpope/vim-abolish'
Bundle 'tpope/vim-endwise'
Bundle 'tpope/vim-eunuch'
Bundle 'tpope/vim-fugitive'
Bundle 'tpope/vim-git'
Bundle 'tpope/vim-haml'
Bundle 'tpope/vim-markdown'
Bundle 'tpope/vim-pastie'
Bundle 'tpope/vim-pathogen'
Bundle 'tpope/vim-ragtag'
Bundle 'tpope/vim-rails'
Bundle 'tpope/vim-repeat'
Bundle 'tpope/vim-speeddating'
Bundle 'tpope/vim-unimpaired'
Bundle 'tpope/vim-vividchalk'
Bundle 'vim-ruby/vim-ruby'
Bundle 'vim-scripts/apachelogs.vim'
Bundle 'vim-scripts/apachestyle'
Bundle 'vim-scripts/bats.vim'
Bundle 'vim-scripts/dhcpd.vim'
Bundle 'vim-scripts/fontzoom.vim'
Bundle 'vim-scripts/iptables'
Bundle 'vim-scripts/nginx.vim'
Bundle 'vim-scripts/tComment'

filetype plugin indent on
