DARWIN=`uname | grep Darwin`

# intial auto config
#
zstyle ':completion:*' auto-description '%d'
zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle ':completion:*' expand prefix suffix
zstyle ':completion:*' format '%d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' ignore-parents parent pwd .. directory
zstyle ':completion:*' insert-unambiguous true
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' list-suffixes true
zstyle ':completion:*' matcher-list '' 'l:|=* r:|=*' 'r:|[._-]=** r:|=**' 'm:{[:lower:]}={[:upper:]} m:{[:lower:][:upper:]}={[:upper:][:lower:]}'
zstyle ':completion:*' menu select=0
zstyle ':completion:*' original true
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' verbose true
zstyle :compinstall filename '/home/force/.zshrc'

autoload -Uz compinit
compinit

# editor
#
export EDITOR=vim
export GIT_EDITOR=vim

# C-x C-e command editing
#
autoload -U edit-command-line
zle -N edit-command-line
bindkey '\C-x\C-e' edit-command-line

# history
#
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory autocd beep extendedglob nomatch notify autopushd

# Fix C-[left] C-[right] behavior
#
bindkey ';5C' forward-word
bindkey ';5D' backward-word

# Fix C-r behavior
#
bindkey '^R' history-incremental-search-backward

# aliases
#
if [ $DARWIN ]; then
  alias ls='ls -G'
else
  alias ls='ls --color=auto'
  alias go=gnome-open
fi
alias gdh="git diff HEAD|gvim -"
alias grep='grep --color=auto'

# command not found
#
if [ -f /etc/zsh_command_not_found ]; then
  source /etc/zsh_command_not_found
fi

# prompts
#
source ~/.zsh/git-prompt/zshrc.sh
PROMPT='%B%F{cyan}%m%F{white}:%F{blue}%~%F{white}%#%b%f '
#RPROMPT="%B%F{white}#%F{cyan}%h %F{white}%* %F{cyan}%D%b%f"
RPROMPT='$(git_super_status)'

# automatically configure make -j option to -j{number of CPUs +1}
#
if [ ! $DARWIN ]; then
  CPUS=`grep processor /proc/cpuinfo|tail -n1|awk '{print $3}'`
  MAKEJOBS=`echo "$CPUS + 2"|bc`
  export MAKEOPTS=-j$MAKEJOBS
fi

# add local bin path to PATH
#
export PATH=/home/force/opt/bin:$PATH

# rvm
#
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"  # This loads RVM into a shell session.

if [ -x ~/.maven_env ]; then
  source ~/.maven_env
fi
