export DARWIN=`uname | grep Darwin`

# intial auto config
#
zstyle ':completion:*' auto-description '%d'
zstyle ':completion:*' completer _expand _complete _ignored _correct _approximate
zstyle ':completion:*' expand prefix suffix
zstyle ':completion:*' format '%d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' ignore-parents parent pwd .. directory
zstyle ':completion:*' insert-unambiguous true
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' list-suffixes true
zstyle ':completion:*' matcher-list '' 'l:|=* r:|=*' 'r:|[._-]=** r:|=**' 'm:{[:lower:]}={[:upper:]} m:{[:lower:][:upper:]}={[:upper:][:lower:]}'
zstyle ':completion:*' menu select=0
zstyle ':completion:*' original true
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' verbose true
zstyle :compinstall filename '/home/force/.zshrc'

autoload -Uz compinit
compinit

# disable zsh which. I HATE IT.
disable which

# editor
#
export EDITOR=vi
export GIT_EDITOR=vi

# C-x C-e command editing
#
autoload -U edit-command-line
zle -N edit-command-line
bindkey '\C-x\C-e' edit-command-line

# history
#
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory autocd beep extendedglob nomatch notify autopushd

# Fix C-[left] C-[right] behavior
#
bindkey ';5C' forward-word
bindkey ';5D' backward-word

# Fix C-r behavior
#
bindkey '^R' history-incremental-search-backward

# aliases
#
if [ $DARWIN ]; then
  alias ls='ls -G'
  alias go=open
else
  alias ls='ls --color=auto'
  alias go=gnome-open
fi

alias gdh="git diff HEAD|gvim -"
alias grep='grep --color=auto'
alias gl=git_log_subway
alias gs='git st'
alias gd='git df'
alias rmorig="find . -name '*.orig' -exec rm \"{}\" \\;"

## ric
alias pview="python /home/force/work/ric/remote_capture/pickle_to_cap.py"

function pycharm() {
  cd ~/opt/pycharm
  bin/pycharm.sh
}

function workon_ric() {
  workon ric2.6
}

function ric() {
  cd ~/work/ric
  workon_ric
}

function pickles() {
  ric
  cd src/nutricate/tests/rparse/pickles
}

# enable pasting of command lines beginning with $. When do you ever mean to
# start a command with '$'?
#
# source: http://stackoverflow.com/questions/68372/what-is-your-single-most-favorite-command-line-trick-using-bash
function $ {
  $@
}

# command not found
#
if [ -f /etc/zsh_command_not_found ]; then
  source /etc/zsh_command_not_found
fi

# prompts
#
source ~/.zsh/git-prompt/zshrc.sh
export ZSH_THEME_GIT_PROMPT_NOCACHE=1
PROMPT='%B%F{cyan}%m%F{white}:%F{blue}%~%F{white}%#%b%f '
#RPROMPT="%B%F{white}#%F{cyan}%h %F{white}%* %F{cyan}%D%b%f"
RPROMPT='$(git_super_status)'

# automatically configure make -j option to -j{number of CPUs +1}
#
if [ ! $DARWIN ]; then
  CPUS=`grep processor /proc/cpuinfo|tail -n1|awk '{print $3}'`
  MAKEJOBS=`echo "$CPUS + 2"|bc`
  export MAKEOPTS=-j$MAKEJOBS
fi

# add local bin path to PATH
#
export PATH=/home/force/opt/bin:$PATH

# rvm
#
[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"  # This loads RVM into a shell session.

if [ -x ~/.maven_env ]; then
  source ~/.maven_env
fi

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
